### ISSUE TITLE
Add `protocol` as argument in `dbConnect()`

### ISSUE THREAD

**Issue by matteodelucchi** [r-dbi/RMariaDB#179]
### Situation
I host a mysql DB in a local docker container. 

docker-compose.yml
```
version: '3.2'

services:
    db:
        image: mysql:8.0
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql-dockerDB/var/lib/mysql:/var/lib/mysql
            - ./dockermnt:/docker-entrypoint-initdb.d
        container_name: mysqlDB
        restart: always
        ports:
            - '6603:3306'
        environment:
            MYSQL_ROOT_PASSWORD: secret
```

I expose the port 6603 to the localhost which allows me to access mysql in the container by i.e.:  
`mysql --host=localhost --port=6603 --user=root --password=secret --protocol=tcp`

### Problem
When I try to connect my local R Studio (not in docker) to mysqlDB via the open port with
```
con <- dbConnect(RMariaDB::MariaDB(),
                  dbname = "dbname",
                  username = "root",
                  password = "secret",
                  port = 6603)
```
I get the error: `Error: Failed to connect: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
`. The same error happens when I specify `host = "localhost"` explicitly.
Which is unexpected, as I don't want to connect to the socket file rather using the TCP network protocol. 
Unfortunately the argument `protocol = "TCP"` is not supported.

### Workaround
I could solve the issue with specifying the protocol in the configuration file:

.my.cnf
```
[destination]
  port=6603
  proto=TCP
```
and then in R specifying the path to the configuration file and groups argument.
```
con <- dbConnect(RMariaDB::MariaDB(),
                  dbname = "dbname",
                  username = "root",
                  password = "secret",
                  groups="destination",
                  default.file = "<path-to-configuration-file>/.my.cnf")
```
### Proposed Solution
In regard of the raising popularity of container stacks, it would be very valuable to have an argument in the method `dbConnect()` to directly specify the protocol type. Then, the workaround with the config file would be obsolete.
I imagine sth like this
```
con <- dbConnect(RMariaDB::MariaDB(),
                  dbname = "dbname",
                  username = "root",
                  password = "secret",
                  port = 6603,
                  protocol = "tcp")
```
