### ISSUE TITLE
How can I configure RMariaDb on a work device? 

### ISSUE THREAD

**Issue by lbui30** [r-dbi/RMariaDB#293]
I cannot figure out how to properly set up RMariaDb.   I tried the .my.cnf file but it didn't really work in the default folder, because of organizational restrictions on which folders have read/write permissions.

Is there a way I can simply pass the information to MariaDb as username and password from a .yml file? Or a way to pass in the location of the .my.cnf that is not in a default location? 

I have started with the former option, but I have not had much luck. 

```yml
# My SQL Config
# Anonymized username and password for reprex
mysql:
  driver: "MySQL ODBC 8.0 ANSI Driver"
  server: "localhost"
  database: "database"
  username: "username"
  password: "password"
```

```r
#Anonymized folder location for reprex
myconfig = config::get(config = "mysql",file = "C:/lbui/secretfolder/ofsecrets/config.yml")
con <- DBI::dbConnect(RMariaDB::MariaDB(),
                      Server   = myconfig$server,
                      dbname   = myconfig$database,
                      UID      = myconfig$user,
                      PWD      = myconfig$password,
                      Port     = 3306)
```
